CREATE SCHEMA IF NOT EXISTS GROOGLE;

CREATE TABLE GROCERY(
ITEM_ID INTEGER NOT NULL,
NAME VARCHAR (500) NOT NULL,
QUANTITY NUMBER(10,0) NOT NULL,
PRICE NUMBER (10,2) NOT NULL,
PRIMARY KEY (ITEM_ID)

);